name: "Build Axs Service"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Service/**'
  pull_request:
    branches:
      - main
      - develop
      - release/*
    paths:
      - 'Service/**'
  workflow_dispatch:
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Generate Version Info
      run: |
        # Run the version script to generate version information
        ./Service/version.sh

    - name: Restore Dependencies
      run: dotnet restore ./Service/src/Api/Api.csproj

    - name: Build Project
      run: dotnet build ./Service/src/Api/Api.csproj --configuration Release --no-restore

    - name: Publish as Self-Contained
      run: dotnet publish ./Service/src/Api/Api.csproj --configuration Release --runtime linux-x64 --self-contained true --output ./dist/axs/publish

    # - name: Copy Scripts to Publish Directory
    #   run: |
    #     if [ -d "./Service/scripts" ]; then
    #       mkdir -p ./dist/bucket/publish/scripts
    #       cp -r ./Service/scripts/* ./dist/bucket/publish/scripts/
    #       echo "Copied scripts to publish directory"
    #     else
    #       echo "Scripts directory not found at ./Service/scripts"
    #       exit 1
    #     fi

    # - name: Upload Bucket Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: bucket
    #     path: ./dist/bucket/publish